// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: teacher.proto

package com.ieven.rpc.protocol.po;

public final class TeacherProto {
  private TeacherProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TeacherOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Teacher)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>optional string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>repeated .Student student_list = 3;</code>
     */
    java.util.List<com.ieven.rpc.protocol.po.StudentProto.Student> 
        getStudentListList();
    /**
     * <code>repeated .Student student_list = 3;</code>
     */
    com.ieven.rpc.protocol.po.StudentProto.Student getStudentList(int index);
    /**
     * <code>repeated .Student student_list = 3;</code>
     */
    int getStudentListCount();
    /**
     * <code>repeated .Student student_list = 3;</code>
     */
    java.util.List<? extends com.ieven.rpc.protocol.po.StudentProto.StudentOrBuilder> 
        getStudentListOrBuilderList();
    /**
     * <code>repeated .Student student_list = 3;</code>
     */
    com.ieven.rpc.protocol.po.StudentProto.StudentOrBuilder getStudentListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Teacher}
   */
  public  static final class Teacher extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Teacher)
      TeacherOrBuilder {
    // Use Teacher.newBuilder() to construct.
    private Teacher(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Teacher() {
      id_ = 0;
      name_ = "";
      studentList_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Teacher(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                studentList_ = new java.util.ArrayList<com.ieven.rpc.protocol.po.StudentProto.Student>();
                mutable_bitField0_ |= 0x00000004;
              }
              studentList_.add(
                  input.readMessage(com.ieven.rpc.protocol.po.StudentProto.Student.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          studentList_ = java.util.Collections.unmodifiableList(studentList_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ieven.rpc.protocol.po.TeacherProto.internal_static_Teacher_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ieven.rpc.protocol.po.TeacherProto.internal_static_Teacher_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ieven.rpc.protocol.po.TeacherProto.Teacher.class, com.ieven.rpc.protocol.po.TeacherProto.Teacher.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>optional int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STUDENT_LIST_FIELD_NUMBER = 3;
    private java.util.List<com.ieven.rpc.protocol.po.StudentProto.Student> studentList_;
    /**
     * <code>repeated .Student student_list = 3;</code>
     */
    public java.util.List<com.ieven.rpc.protocol.po.StudentProto.Student> getStudentListList() {
      return studentList_;
    }
    /**
     * <code>repeated .Student student_list = 3;</code>
     */
    public java.util.List<? extends com.ieven.rpc.protocol.po.StudentProto.StudentOrBuilder> 
        getStudentListOrBuilderList() {
      return studentList_;
    }
    /**
     * <code>repeated .Student student_list = 3;</code>
     */
    public int getStudentListCount() {
      return studentList_.size();
    }
    /**
     * <code>repeated .Student student_list = 3;</code>
     */
    public com.ieven.rpc.protocol.po.StudentProto.Student getStudentList(int index) {
      return studentList_.get(index);
    }
    /**
     * <code>repeated .Student student_list = 3;</code>
     */
    public com.ieven.rpc.protocol.po.StudentProto.StudentOrBuilder getStudentListOrBuilder(
        int index) {
      return studentList_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      for (int i = 0; i < studentList_.size(); i++) {
        output.writeMessage(3, studentList_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      for (int i = 0; i < studentList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, studentList_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ieven.rpc.protocol.po.TeacherProto.Teacher)) {
        return super.equals(obj);
      }
      com.ieven.rpc.protocol.po.TeacherProto.Teacher other = (com.ieven.rpc.protocol.po.TeacherProto.Teacher) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getName()
          .equals(other.getName());
      result = result && getStudentListList()
          .equals(other.getStudentListList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (getStudentListCount() > 0) {
        hash = (37 * hash) + STUDENT_LIST_FIELD_NUMBER;
        hash = (53 * hash) + getStudentListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ieven.rpc.protocol.po.TeacherProto.Teacher parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ieven.rpc.protocol.po.TeacherProto.Teacher parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ieven.rpc.protocol.po.TeacherProto.Teacher parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ieven.rpc.protocol.po.TeacherProto.Teacher parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ieven.rpc.protocol.po.TeacherProto.Teacher parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ieven.rpc.protocol.po.TeacherProto.Teacher parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ieven.rpc.protocol.po.TeacherProto.Teacher parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ieven.rpc.protocol.po.TeacherProto.Teacher parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ieven.rpc.protocol.po.TeacherProto.Teacher parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ieven.rpc.protocol.po.TeacherProto.Teacher parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ieven.rpc.protocol.po.TeacherProto.Teacher prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Teacher}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Teacher)
        com.ieven.rpc.protocol.po.TeacherProto.TeacherOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ieven.rpc.protocol.po.TeacherProto.internal_static_Teacher_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ieven.rpc.protocol.po.TeacherProto.internal_static_Teacher_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ieven.rpc.protocol.po.TeacherProto.Teacher.class, com.ieven.rpc.protocol.po.TeacherProto.Teacher.Builder.class);
      }

      // Construct using com.ieven.rpc.protocol.po.TeacherProto.Teacher.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getStudentListFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        if (studentListBuilder_ == null) {
          studentList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          studentListBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ieven.rpc.protocol.po.TeacherProto.internal_static_Teacher_descriptor;
      }

      public com.ieven.rpc.protocol.po.TeacherProto.Teacher getDefaultInstanceForType() {
        return com.ieven.rpc.protocol.po.TeacherProto.Teacher.getDefaultInstance();
      }

      public com.ieven.rpc.protocol.po.TeacherProto.Teacher build() {
        com.ieven.rpc.protocol.po.TeacherProto.Teacher result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ieven.rpc.protocol.po.TeacherProto.Teacher buildPartial() {
        com.ieven.rpc.protocol.po.TeacherProto.Teacher result = new com.ieven.rpc.protocol.po.TeacherProto.Teacher(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        result.name_ = name_;
        if (studentListBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            studentList_ = java.util.Collections.unmodifiableList(studentList_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.studentList_ = studentList_;
        } else {
          result.studentList_ = studentListBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ieven.rpc.protocol.po.TeacherProto.Teacher) {
          return mergeFrom((com.ieven.rpc.protocol.po.TeacherProto.Teacher)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ieven.rpc.protocol.po.TeacherProto.Teacher other) {
        if (other == com.ieven.rpc.protocol.po.TeacherProto.Teacher.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (studentListBuilder_ == null) {
          if (!other.studentList_.isEmpty()) {
            if (studentList_.isEmpty()) {
              studentList_ = other.studentList_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureStudentListIsMutable();
              studentList_.addAll(other.studentList_);
            }
            onChanged();
          }
        } else {
          if (!other.studentList_.isEmpty()) {
            if (studentListBuilder_.isEmpty()) {
              studentListBuilder_.dispose();
              studentListBuilder_ = null;
              studentList_ = other.studentList_;
              bitField0_ = (bitField0_ & ~0x00000004);
              studentListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getStudentListFieldBuilder() : null;
            } else {
              studentListBuilder_.addAllMessages(other.studentList_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ieven.rpc.protocol.po.TeacherProto.Teacher parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ieven.rpc.protocol.po.TeacherProto.Teacher) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>optional int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.ieven.rpc.protocol.po.StudentProto.Student> studentList_ =
        java.util.Collections.emptyList();
      private void ensureStudentListIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          studentList_ = new java.util.ArrayList<com.ieven.rpc.protocol.po.StudentProto.Student>(studentList_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.ieven.rpc.protocol.po.StudentProto.Student, com.ieven.rpc.protocol.po.StudentProto.Student.Builder, com.ieven.rpc.protocol.po.StudentProto.StudentOrBuilder> studentListBuilder_;

      /**
       * <code>repeated .Student student_list = 3;</code>
       */
      public java.util.List<com.ieven.rpc.protocol.po.StudentProto.Student> getStudentListList() {
        if (studentListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(studentList_);
        } else {
          return studentListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Student student_list = 3;</code>
       */
      public int getStudentListCount() {
        if (studentListBuilder_ == null) {
          return studentList_.size();
        } else {
          return studentListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Student student_list = 3;</code>
       */
      public com.ieven.rpc.protocol.po.StudentProto.Student getStudentList(int index) {
        if (studentListBuilder_ == null) {
          return studentList_.get(index);
        } else {
          return studentListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Student student_list = 3;</code>
       */
      public Builder setStudentList(
          int index, com.ieven.rpc.protocol.po.StudentProto.Student value) {
        if (studentListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStudentListIsMutable();
          studentList_.set(index, value);
          onChanged();
        } else {
          studentListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Student student_list = 3;</code>
       */
      public Builder setStudentList(
          int index, com.ieven.rpc.protocol.po.StudentProto.Student.Builder builderForValue) {
        if (studentListBuilder_ == null) {
          ensureStudentListIsMutable();
          studentList_.set(index, builderForValue.build());
          onChanged();
        } else {
          studentListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Student student_list = 3;</code>
       */
      public Builder addStudentList(com.ieven.rpc.protocol.po.StudentProto.Student value) {
        if (studentListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStudentListIsMutable();
          studentList_.add(value);
          onChanged();
        } else {
          studentListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Student student_list = 3;</code>
       */
      public Builder addStudentList(
          int index, com.ieven.rpc.protocol.po.StudentProto.Student value) {
        if (studentListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStudentListIsMutable();
          studentList_.add(index, value);
          onChanged();
        } else {
          studentListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Student student_list = 3;</code>
       */
      public Builder addStudentList(
          com.ieven.rpc.protocol.po.StudentProto.Student.Builder builderForValue) {
        if (studentListBuilder_ == null) {
          ensureStudentListIsMutable();
          studentList_.add(builderForValue.build());
          onChanged();
        } else {
          studentListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Student student_list = 3;</code>
       */
      public Builder addStudentList(
          int index, com.ieven.rpc.protocol.po.StudentProto.Student.Builder builderForValue) {
        if (studentListBuilder_ == null) {
          ensureStudentListIsMutable();
          studentList_.add(index, builderForValue.build());
          onChanged();
        } else {
          studentListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Student student_list = 3;</code>
       */
      public Builder addAllStudentList(
          java.lang.Iterable<? extends com.ieven.rpc.protocol.po.StudentProto.Student> values) {
        if (studentListBuilder_ == null) {
          ensureStudentListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, studentList_);
          onChanged();
        } else {
          studentListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Student student_list = 3;</code>
       */
      public Builder clearStudentList() {
        if (studentListBuilder_ == null) {
          studentList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          studentListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Student student_list = 3;</code>
       */
      public Builder removeStudentList(int index) {
        if (studentListBuilder_ == null) {
          ensureStudentListIsMutable();
          studentList_.remove(index);
          onChanged();
        } else {
          studentListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Student student_list = 3;</code>
       */
      public com.ieven.rpc.protocol.po.StudentProto.Student.Builder getStudentListBuilder(
          int index) {
        return getStudentListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Student student_list = 3;</code>
       */
      public com.ieven.rpc.protocol.po.StudentProto.StudentOrBuilder getStudentListOrBuilder(
          int index) {
        if (studentListBuilder_ == null) {
          return studentList_.get(index);  } else {
          return studentListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Student student_list = 3;</code>
       */
      public java.util.List<? extends com.ieven.rpc.protocol.po.StudentProto.StudentOrBuilder> 
           getStudentListOrBuilderList() {
        if (studentListBuilder_ != null) {
          return studentListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(studentList_);
        }
      }
      /**
       * <code>repeated .Student student_list = 3;</code>
       */
      public com.ieven.rpc.protocol.po.StudentProto.Student.Builder addStudentListBuilder() {
        return getStudentListFieldBuilder().addBuilder(
            com.ieven.rpc.protocol.po.StudentProto.Student.getDefaultInstance());
      }
      /**
       * <code>repeated .Student student_list = 3;</code>
       */
      public com.ieven.rpc.protocol.po.StudentProto.Student.Builder addStudentListBuilder(
          int index) {
        return getStudentListFieldBuilder().addBuilder(
            index, com.ieven.rpc.protocol.po.StudentProto.Student.getDefaultInstance());
      }
      /**
       * <code>repeated .Student student_list = 3;</code>
       */
      public java.util.List<com.ieven.rpc.protocol.po.StudentProto.Student.Builder> 
           getStudentListBuilderList() {
        return getStudentListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.ieven.rpc.protocol.po.StudentProto.Student, com.ieven.rpc.protocol.po.StudentProto.Student.Builder, com.ieven.rpc.protocol.po.StudentProto.StudentOrBuilder> 
          getStudentListFieldBuilder() {
        if (studentListBuilder_ == null) {
          studentListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.ieven.rpc.protocol.po.StudentProto.Student, com.ieven.rpc.protocol.po.StudentProto.Student.Builder, com.ieven.rpc.protocol.po.StudentProto.StudentOrBuilder>(
                  studentList_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          studentList_ = null;
        }
        return studentListBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Teacher)
    }

    // @@protoc_insertion_point(class_scope:Teacher)
    private static final com.ieven.rpc.protocol.po.TeacherProto.Teacher DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ieven.rpc.protocol.po.TeacherProto.Teacher();
    }

    public static com.ieven.rpc.protocol.po.TeacherProto.Teacher getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Teacher>
        PARSER = new com.google.protobuf.AbstractParser<Teacher>() {
      public Teacher parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Teacher(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Teacher> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Teacher> getParserForType() {
      return PARSER;
    }

    public com.ieven.rpc.protocol.po.TeacherProto.Teacher getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Teacher_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Teacher_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rteacher.proto\032\rstudent.proto\"C\n\007Teache" +
      "r\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\036\n\014student_l" +
      "ist\030\003 \003(\0132\010.StudentB)\n\031com.ieven.rpc.pro" +
      "tocol.poB\014TeacherProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ieven.rpc.protocol.po.StudentProto.getDescriptor(),
        }, assigner);
    internal_static_Teacher_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Teacher_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Teacher_descriptor,
        new java.lang.String[] { "Id", "Name", "StudentList", });
    com.ieven.rpc.protocol.po.StudentProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
